In [1]:
# Afficher le fichier texte sudoku
import numpy as np
with open("sudoku2.txt", 'r') as file:
    lines = file.readlines()   
sudoku_list = []
for line in lines:
    line = [int (char) if char != '_' else 0 for char in line.strip()]
    sudoku_list.append(line)
sudoku_list

N = 9
def printing (sudoku_list):
    for i in range (N):
        for j in range (N):
            print(sudoku_list[i][j], end = " ")
        print()

printing(sudoku_list)

7 0 0 9 2 0 4 0 0 
0 0 0 0 0 0 7 0 0 
0 0 4 0 0 8 3 1 2 
4 0 0 0 0 2 5 0 0 
2 0 0 0 1 0 0 0 3 
0 0 8 5 0 0 0 0 4 
8 4 3 2 0 0 6 0 0 
0 0 5 0 0 0 0 0 0 
0 0 2 0 6 4 0 0 5 


In [4]:
# RESOLUTION DE SUDOKU AVEC LA METHODE DU BACKTRACKING
import numpy as np

# Fonction pour vérifier si une valeur peut être placée dans une case donnée du sudoku
def is_valid_move(sudoku, row, col, num):
    for i in range(9):
        if sudoku[row][i] == num or sudoku[i][col] == num:
            return False

    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(start_row, start_row + 3):
        for j in range(start_col, start_col + 3):
            if sudoku[i][j] == num:
                return False
    return True

# Fonction pour résoudre le sudoku
def solve_sudoku(sudoku):
    for row in range(9):
        for col in range(9):
            if sudoku[row][col] == 0:
                for num in range(1, 10):
                    if is_valid_move(sudoku, row, col, num):
                        sudoku[row][col] = num
                        if solve_sudoku(sudoku):
                            return True
                        sudoku[row][col] = 0
                return False
    return True

# Lecture du sudoku depuis le fichier texte
with open("sudoku2.txt", 'r') as file:
    lines = file.readlines()

sudoku_list = []
for line in lines:
    line = [int(char) if char != '_' else 0 for char in line.strip()]
    sudoku_list.append(line)

# Convertir la liste en un tableau numpy
sudoku = np.array(sudoku_list)

# Résoudre le sudoku
if solve_sudoku(sudoku):
    # Imprimer la solution
    print(sudoku)
else:
    print("Aucune solution trouvée.")


[[7 8 1 9 2 3 4 5 6]
 [3 2 6 1 4 5 7 8 9]
 [5 9 4 6 7 8 3 1 2]
 [4 1 9 3 8 2 5 6 7]
 [2 5 7 4 1 6 8 9 3]
 [6 3 8 5 9 7 1 2 4]
 [8 4 3 2 5 9 6 7 1]
 [9 6 5 7 3 1 2 4 8]
 [1 7 2 8 6 4 9 3 5]]


In [3]:
import pygame
import numpy as np

# Initialisation de Pygame
pygame.init()

# Définition des couleurs
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
FONT_SIZE = 36

# Définir la taille de la fenêtre
WINDOW_SIZE = 540
CELL_SIZE = WINDOW_SIZE // 9

# Créer la fenêtre Pygame
screen = pygame.display.set_mode((WINDOW_SIZE, WINDOW_SIZE))
pygame.display.set_caption("Sudoku Solver")

# Charger le sudoku depuis le fichier texte
with open("sudoku2.txt", 'r') as file:
    lines = file.readlines()

sudoku_list = []
for line in lines:
    line = [int(char) if char != '_' else 0 for char in line.strip()]
    sudoku_list.append(line)

# Convertir la liste en un tableau numpy
sudoku = np.array(sudoku_list)

# Fonction pour dessiner le sudoku sur l'écran
def draw_sudoku():
    screen.fill(WHITE)
    font = pygame.font.Font(None, FONT_SIZE)

    for row in range(9):
        for col in range(9):
            num = sudoku[row][col]
            if num != 0:
                text = font.render(str(num), True, BLACK)
                x = col * CELL_SIZE + CELL_SIZE // 2 - text.get_width() // 2
                y = row * CELL_SIZE + CELL_SIZE // 2 - text.get_height() // 2
                screen.blit(text, (x, y))

    # Dessiner les lignes du sudoku
    for i in range(10):
        if i % 3 == 0:
            pygame.draw.line(screen, BLACK, (i * CELL_SIZE, 0), (i * CELL_SIZE, WINDOW_SIZE), 3)
            pygame.draw.line(screen, BLACK, (0, i * CELL_SIZE), (WINDOW_SIZE, i * CELL_SIZE), 3)
        else:
            pygame.draw.line(screen, BLACK, (i * CELL_SIZE, 0), (i * CELL_SIZE, WINDOW_SIZE), 1)
            pygame.draw.line(screen, BLACK, (0, i * CELL_SIZE), (WINDOW_SIZE, i * CELL_SIZE), 1)

# Fonction pour résoudre le sudoku
def solve_sudoku_gui():
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()

    for row in range(9):
        for col in range(9):
            if sudoku[row][col] == 0:
                for num in range(1, 10):
                    if is_valid_move(sudoku, row, col, num):
                        sudoku[row][col] = num
                        draw_sudoku()
                        pygame.display.update()
                        pygame.time.delay(100)  # Pause pour une meilleure visualisation
                        if solve_sudoku_gui():
                            return True
                        sudoku[row][col] = 0
                        draw_sudoku()
                        pygame.display.update()
                return False
    return True

# Fonction pour vérifier si une valeur peut être placée dans une case donnée du sudoku
def is_valid_move(sudoku, row, col, num):
    for i in range(9):
        if sudoku[row][i] == num or sudoku[i][col] == num:
            return False

    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(start_row, start_row + 3):
        for j in range(start_col, start_col + 3):
            if sudoku[i][j] == num:
                return False
    return True

# Résoudre le sudoku en utilisant Pygame
solve_sudoku_gui()

# Boucle principale Pygame
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

pygame.quit()
